In [1]:
import pandas as pd

In [3]:
file_1="video_with_meta_data_and_transcript.csv"

df=pd.read_csv(file_1)
df.head()

,video_id,title,length,publish_date,views,url,text,start,duration
0,wKw1tpN7NVE,Do Something Difficult Every Day | AMA #1 - As...,293.0,20200219.0,147230.0,https://www.youtube.com/watch?v=wKw1tpN7NVE,Miriam asks hello Lex in your interview,0.030,6.599
1,wKw1tpN7NVE,Do Something Difficult Every Day | AMA #1 - As...,293.0,20200219.0,147230.0,https://www.youtube.com/watch?v=wKw1tpN7NVE,with Arianna you have mentioned that,4.140,5.160
2,wKw1tpN7NVE,Do Something Difficult Every Day | AMA #1 - As...,293.0,20200219.0,147230.0,https://www.youtube.com/watch?v=wKw1tpN7NVE,suffering is good for the soul where did,6.629,5.821
3,wKw1tpN7NVE,Do Something Difficult Every Day | AMA #1 - As...,293.0,20200219.0,147230.0,https://www.youtube.com/watch?v=wKw1tpN7NVE,that come from what is your belief,9.300,5.040
4,wKw1tpN7NVE,Do Something Difficult Every Day | AMA #1 - As...,293.0,20200219.0,147230.0,https://www.youtube.com/watch?v=wKw1tpN7NVE,system for maintaining self-discipline,12.450,4.970

In [4]:
df.columns

Index(['video_id', 'title', 'length', 'publish_date', 'views', 'url', 'text',
       'start', 'duration'],
      dtype='object')

In [5]:
df2=pd.read_csv("videos.csv")

df2.head()

,Title,Length,video_id,publish_date,views,url
0,Do Something Difficult Every Day | AMA #1 - As...,293.0,wKw1tpN7NVE,20200219.0,147230.0,https://www.youtube.com/watch?v=wKw1tpN7NVE
1,NaN,NaN,NaN,NaN,NaN,NaN
2,How to learn and master a new skill,578.0,_ySbzVXiwzQ,20201121.0,807817.0,https://www.youtube.com/watch?v=_ySbzVXiwzQ
3,NaN,NaN,NaN,NaN,NaN,NaN
4,Make Disadvantage Your Superpower | Lex Fridma...,517.0,pXEl0R1BX-g,20200629.0,151610.0,https://www.youtube.com/watch?v=pXEl0R1BX-g

In [6]:
df2.columns

Index(['Title', 'Length', 'video_id', 'publish_date', 'views', 'url'], dtype='object')

In [8]:
from doc_loader import Csv_Loader

csv_path = "video_with_meta_data_and_transcript.csv"

loader = Csv_Loader(csv_path)
docs = loader.load()

print(len(docs))
print(docs[2])

5008
page_content='suffering is good for the soul where did' metadata={'video_id': 'wKw1tpN7NVE', 'title': 'Do Something Difficult Every Day | AMA #1 - Ask Me Anything with Lex Fridman', 'start': 6.629, 'duration': 5.821, 'url': 'https://www.youtube.com/watch?v=wKw1tpN7NVE', 'publish_date': 20200219.0, 'views': 147230.0, 'length': 293.0, 'citation_url': 'https://www.youtube.com/watch?v=wKw1tpN7NVE&t=6s'}

ModuleNotFoundError: No module named 'langchain_chroma'